
grade1 = [
    ("𧵑", "của"), ("吧", "và"), ("𱺵", "là"), ("𠬠", "một"), ("固", "có"), ("𠊛", "người"), ("𥪝", "trong"), ("特", "được"), 
    ("空", "không"), ("㐌", "đã"), ("唄", "với"), ("朱", "cho"), ("各", "các"), ("碎", "tôi"), ("於", "ở"), ("翁", "ông"), 
    ("𧗱", "về"), ("底", "để"), ("拱", "cũng"), ("𦤾", "đến"), ("呢", "này"), ("𠓨", "vào"), ("𡗉", "nhiều"), ("偀", "anh"), 
    ("妬", "đó"), ("如", "như"), ("仍", "nhưng"), ("欺", "khi"), ("𨕭", "trên"), ("𫥨", "ra"), ("越", "việt"), ("南", "nam"), 
    ("𦓡", "mà"), ("體", "thể"), ("沛", "phải"), ("吏", "lại"), ("群", "còn"), ("𠱊", "sẽ"), ("㖘", "thì"), ("𢆥", "năm"), 
    ("爫", "làm"), ("茹", "nhà"), ("𨉟", "mình"), ("𠫾", "đi"), ("𡥵", "con"), ("在", "tại"), ("𠄩", "hai"), ("備", "bị"), 
    ("被", "bị"), ("役", "việc"), ("只", "chỉ"), ("事", "sự"), ("遶", "theo"), ("丐", "cái"), ("爲", "vì"), ("欣", "hơn"), 
    ("呐", "nói"), ("姑", "cô"), ("𣈜", "ngày"), ("㵋", "mới"), ("𨖲", "lên"), ("慄", "rất"), ("戶", "họ"), ("婆", "bà"), 
    ("局", "cuộc"), ("册", "sách"), ("垌", "đồng"), ("同", "đồng"), ("銅", "đồng"), ("𡢐", "sau"), ("當", "đang"), ("咍", "hay"), 
    ("𤯩", "sống"), ("𢧚", "nên"), ("别", "biết"), ("𧡊", "thấy"), ("耒", "rồi"), ("誠", "thành"), ("成", "thành"), ("城", "thành"), 
    ("吻", "vẫn"), ("恪", "khác"), ("𠄼", "năm")
]

grade2 = [
    ("作", "tác"), ("品", "phẩm"), ("化", "hoá"), ("家", "gia"), ("庭", "đình"), ("組", "tổ"), ("織", "chức"), ("庯", "phố"), 
    ("界", "giới"), ("河", "hà"), ("内", "nội"), ("作", "tác"), ("者", "giả"), ("藝", "nghề"), ("間", "gian"), ("畢", "tất"), 
    ("先", "tiên"), ("體", "thể"), ("歷", "lịch"), ("史", "sử"), ("婦", "phụ"), ("家", "gia"), ("社", "xã"), ("出", "xuất"), 
    ("警", "cảnh"), ("察", "sát"), ("研", "nghiên"), ("究", "cứu"), ("扒", "bắt"), ("現", "hiện"), ("雖", "tuy"), ("然", "nhiên"), 
    ("藝", "nghề"), ("士", "sĩ"), ("使", "sứ"), ("渃", "nước"), ("伮", "nó"), ("細", "tới"), ("戈", "qua"), ("哿", "cả"), 
    ("之", "gì"), ("低", "đây"), ("数", "số"), ("歲", "tuổi"), ("次", "thứ"), ("奇", "kỳ"), ("期", "kỳ"), ("圻", "kỳ"), 
    ("㛪", "em"), ("一", "nhất"), ("𠓀", "trước"), ("伴", "bạn"), ("意", "ý"), ("影", "ảnh"), ("朋", "bằng"), ("凭", "bằng"), 
    ("芇", "nào"), ("頭", "đầu"), ("投", "đầu"), ("阮", "nguyễn"), ("哴", "rằng"), ("革", "cách"), ("格", "cách"), ("曰", "viết"), 
    ("尋", "tìm"), ("𣅶", "lúc"), ("理", "lý"), ("李", "lý"), ("正", "chính"), ("政", "chính"), ("𧘇", "ấy"), ("𣎃", "tháng"), 
    ("會", "hội"), ("憢", "nhau"), ("𣗓", "chưa"), ("時", "thời"), ("吝", "lần"), ("由", "do"), ("𣃣", "vừa"), ("㦖", "muốn"), 
    ("文", "văn"), ("工", "công"), ("卷", "cuốn"), ("捲", "cuốn"), ("條", "điều"), ("花", "hoa"), ("華", "hoa"), ("𡘯", "lớn"), 
    ("埃", "ai"), ("𠀧", "ba"), ("爸", "ba"), ("㗂", "tiếng"), ("塘", "đường"), ("堂", "đường"), ("糖", "đường"), ("世", "thế"), 
    ("替", "thế"), ("勢", "thế"), ("曾", "từng"), ("𫢩", "nay"), ("坭", "nơi"), ("形", "hình"), ("錢", "tiền"), ("前", "tiền"), 
    ("些", "ta"), ("南", "nam"), ("越", "việt"), ("中", "trung"), ("𠮩", "nếu"), ("𥘷", "trẻ"), ("𠸜", "tên"), ("𥏌", "tên"), 
    ("實", "thật"), ("媄", "mẹ"), ("勤", "cần"), ("𡀯", "chuyện"), ("每", "mỗi"), ("芒", "mang"), ("調", "đều"), ("姉", "chị"), 
    ("車", "xe"), ("禮", "lễ"), ("迻", "đưa"), ("𥆾", "nhìn"), ("國", "quốc"), ("添", "thêm"), ("高", "cao"), ("部", "bộ"), 
    ("步", "bộ"), ("隻", "chiếc"), ("𤞦", "mọi"), ("爭", "tranh"), ("幀", "tranh"), ("𢬣", "tay"), ("𢝙", "vui"), ("信", "tin"), 
    ("吀", "xin"), ("民", "dân"), ("省", "tỉnh"), ("過", "quá"), ("咹", "ăn"), ("𢞅", "yêu"), ("𡨌", "giữa"), ("𡞕", "vợ"), 
    ("讀", "đọc"), ("𣩂", "chết"), ("場", "trường"), ("行", "hàng"), ("航", "hàng"), ("𥙩", "lấy"), ("𦖑", "nghe"), ("𢢲", "đẹp"), 
    ("自", "tự"), ("字", "tự"), ("𠢞", "giúp"), ("𡮈", "nhỏ"), ("書", "thư"), ("𠯆", "nữa"), ("常", "thường"), ("學", "học"), 
    ("東", "đông"), ("𠅍", "mất"), ("𨑜", "xuống"), ("坦", "đất"), ("半", "bán"), ("𧸝", "bán"), ("併", "tính"), ("對", "đối"), 
    ("類", "loại"), ("或", "hoặc"), ("𩈘", "mặt"), ("䀡", "xem"), ("情", "tình"), ("外", "ngoài"), ("边", "bên"), ("𣋀", "sao"), 
    ("牢", "sao"), ("𤀘", "vùng"), ("丕", "vậy"), ("妝", "trang"), ("張", "trang"), ("𠳒", "lời"), ("歇", "hết"), ("陳", "trần"), 
    ("𠇍", "mấy"), ("認", "nhận"), ("兜", "đâu"), ("青", "thanh"), ("清", "thanh"), ("聲", "thanh"), ("古", "cổ"), ("𤳄", "bởi"), 
    ("𢚸", "lòng"), ("幅", "bức"), ("兆", "triệu"), ("𣦍", "ngay"), ("𧵆", "gần"), ("𧷸", "mua"), ("用", "dùng"), ("𫯳", "chồng"), 
    ("分", "phần"), ("女", "nữ"), ("𧿨", "trở"), ("曠", "khoảng"), ("𠸥", "kể"), ("觀", "quan"), ("關", "quan"), ("無", "vô"), 
    ("員", "viên"), ("湖", "hồ"), ("糊", "hồ"), ("拠", "cứ"), ("廊", "làng"), ("春", "xuân"), ("𢣂", "nghĩ"), ("報", "báo"), 
    ("本", "bản"), ("版", "bản"), ("適", "thích"), ("釋", "thích"), ("傷", "thương"), ("總", "tổng"), ("𣘃", "cây"), ("傳", "truyện"), 
    ("𠁀", "đời"), ("𤲂", "dưới"), ("法", "pháp"), ("心", "tâm"), ("賖", "xa"), ("﨤", "gặp"), ("眜", "mắt"), ("北", "bắc"), 
    ("明", "minh"), ("元", "nguyên"), ("原", "nguyên"), ("四", "tư"), ("𠶢", "dù"), ("價", "giá"), ("𡎥", "ngồi"), ("大", "đại"), 
    ("代", "đại"), ("𣇞", "giờ"), ("身", "thân"), ("𦘧", "vẽ"), ("輪", "luôn"), ("司", "ty"), ("𡛔", "gái"), ("造", "tạo"), 
    ("共", "cộng"), ("𣋚", "hôm"), ("务", "mùa"), ("庄", "chẳng"), ("推", "thôi"), ("牟", "màu"), ("𢲧", "gây"), ("解", "giải"), 
    ("句", "câu"), ("德", "đức"), ("點", "điểm"), ("𡨹", "giữ"), ("卒", "tốt"), ("務", "vụ"), ("𡗶", "trời"), ("𢖵", "nhớ"), 
    ("𠳨", "hỏi"), ("𦣰", "nằm"), ("想", "tưởng"), ("沔", "miền"), ("屬", "thuộc"), ("注", "chú"), ("排", "bài"), ("𨖅", "sang"), 
    ("鐄", "vàng"), ("旬", "tuần"), ("眾", "chúng"), ("𣛠", "máy"), ("金", "kim"), ("今", "kim"), ("洲", "châu"), ("珠", "châu"), 
    ("山", "sơn"), ("𡥙", "cháu"), ("菭", "đầy"), ("日", "nhật"), ("𠁂", "đứa"), ("𨱽", "dài"), ("樂", "nhạc"), ("班", "ban"), 
    ("都", "đủ"), ("𣎀", "đêm"), ("娘", "nàng"), ("詩", "thi"), ("曉", "hiểu"), ("西", "tây"), ("噠", "đặt"), ("評", "bình"), 
    ("瓶", "bình"), ("平", "bình"), ("𨷶", "cửa"), ("義", "nghĩa"), ("𠬃", "bỏ"), ("𥹰", "lâu"), ("房", "phòng"), ("防", "phòng"), 
    ("位", "vị"), ("𠹲", "chứ"), ("𡗋", "lắm"), ("𡦂", "chữ"), ("塊", "khỏi"), ("𣷷", "biển"), ("秋", "thu"), ("求", "cầu"), 
    ("𤎜", "sáng"), ("𧼋", "chạy"), ("蹎", "chân"), ("呈", "trình"), ("程", "trình"), ("𪰂", "phía"), ("𤤰", "vua"), ("人", "nhân"), 
    ("仁", "nhân"), ("保", "bảo"), ("𠸒", "bảo"), ("名", "danh"), ("區", "khu"), ("立", "lập"), ("術", "thuật"), ("賴", "trái"), 
    ("𣛤", "trái"), ("強", "càng"), ("玉", "ngọc"), ("客", "khách"), ("噲", "gọi"), ("龍", "long"), ("欱", "hát"), ("𠄧", "vài"), 
    ("統", "thống")
]

grade3 = [
    ("遊", "du"), ("歷", "lịch"), ("章", "chương"), ("問", "vấn"), ("題", "đề"), ("展", "triển"), ("𣊾", "bây"), ("決", "quyết"), 
    ("遺", "di"), ("産", "sản"), ("俗", "tục"), ("𢷮", "đổi"), ("者", "giả"), ("仕", "xảy"), ("衛", "vệ"), ("𢩿", "sẻ"), 
    ("幸", "hạnh"), ("福", "phước"), ("科", "khoa"), ("出", "xuất"), ("巾", "khăn"), ("精", "tinh"), ("系", "hệ"), ("饒", "nhiêu"), 
    ("案", "án"), ("響", "hưởng"), ("甚", "thậm"), ("至", "chí"), ("地", "địa"), ("果", "quả"), ("産", "sản"), ("出", "xuất"), 
    ("合", "hợp"), ("産", "sản"), ("話", "thoại"), ("係", "hệ"), ("教", "giáo"), ("育", "dục"), ("恩", "ơn"), ("題", "đề"), 
    ("𨷑", "mở"), ("朝", "chiều"), ("公", "công"), ("𨀈", "bước"), ("終", "chung"), ("𢮪", "chọn"), ("少", "thiếu"), ("現", "hiện"), 
    ("𨅸", "đứng"), ("扒", "bắt"), ("孟", "mạnh"), ("𡮣", "bé"), ("視", "thị"), ("市", "thị"), ("示", "thị"), ("級", "cấp"), 
    ("和", "hoà"), ("𣇜", "buổi"), ("𢞂", "buồn"), ("蘭", "lan"), ("跢", "đá"), ("𥒥", "đá"), ("舅", "cậu"), ("𨔈", "chơi"), 
    ("物", "vật"), ("𫇰", "cũ"), ("聯", "liên"), ("連", "liên"), ("𢘾", "nhờ"), ("吒", "cha"), ("廚", "chùa"), ("家", "gia"), 
    ("加", "gia"), ("電", "điện"), ("香", "hương"), ("鄉", "hương"), ("𠖤", "bay"), ("𢗼", "lo"), ("隊", "đội"), ("𡊲", "chỗ"), 
    ("𨤔", "vẻ"), ("定", "định"), ("唭", "cười"), ("增", "tăng"), ("生", "sinh"), ("太", "thái"), ("度", "độ"), ("弓", "cung"), 
    ("宮", "cung"), ("𡖡", "nhóm"), ("𫀅", "coi"), ("軍", "quân"), ("𤖹", "lớp"), ("安", "an"), ("仉", "kẻ"), ("病", "bệnh"), 
    ("洋", "dương"), ("徊", "hồi"), ("回", "hồi"), ("藝", "nghề"), ("𠊟", "thằng"), ("堆", "đôi"), ("𠭤", "trả"), ("全", "toàn"), 
    ("柴", "sài"), ("最", "tối"), ("滝", "sông"), ("紅", "hồng"), ("印", "in"), ("打", "đánh"), ("𠃣", "ít"), ("飞", "phi"), 
    ("箕", "kia"), ("博", "bác"), ("伯", "bác"), ("艚", "tàu"), ("邦", "bang"), ("士", "sĩ"), ("警", "cảnh"), ("景", "cảnh"), 
    ("預", "dự"), ("化", "hoá"), ("𤽸", "trắng"), ("黨", "đảng"), ("𧁷", "khó"), ("命", "mạng"), ("界", "giới"), ("阿", "a"), 
    ("偨", "thầy"), ("糝", "tấm"), ("𤗲", "tấm"), ("𩃳", "bóng"), ("𣈖", "bóng"), ("𤊡", "bóng"), ("払", "chàng"), ("𧆄", "thuốc"), 
    ("襖", "áo"), ("奥", "áo"), ("年", "niên"), ("𠸗", "xưa"), ("源", "nguồn"), ("劍", "kiếm"), ("庭", "đình"), ("光", "quang"), 
    ("停", "đừng"), ("蘿", "lá"), ("𠹾", "chịu"), ("聰", "thông"), ("通", "thông"), ("財", "tài"), ("才", "tài"), ("材", "tài"), 
    ("子", "tử"), ("長", "trưởng"), ("䏧", "da"), ("河", "hà"), ("權", "quyền"), ("𤾓", "trăm"), ("𦓅", "già"), ("犯", "phạm"), 
    ("𪝳", "hắn"), ("接", "tiếp"), ("陣", "trận"), ("衝", "xong"), ("譯", "dịch"), ("院", "viện"), ("撑", "xanh"), ("𥐉", "ngắn"), 
    ("𦊚", "bốn"), ("貪", "tham"), ("參", "tham"), ("王", "vương"), ("神", "thần"), ("易", "dễ"), ("囉", "la"), ("探", "thăm"), 
    ("庯", "phố"), ("黰", "đen"), ("式", "thức"), ("道", "đạo"), ("圖", "đồ"), ("途", "đồ"), ("機", "cơ"), ("基", "cơ"), 
    ("海", "hải"), ("布", "bố"), ("佈", "bố"), ("𢂞", "bố"), ("𢜝", "sợ"), ("天", "thiên"), ("主", "chủ"), ("𨑻", "đem"), 
    ("埋", "mai"), ("𢟘", "chắc"), ("志", "chí"), ("㕵", "uống"), ("指", "chỉ"), ("雖", "tuy"), ("手", "thủ"), ("首", "thủ"), 
    ("默", "mặc"), ("𧹼", "đỏ"), ("泣", "khắp"), ("唏", "hơi"), ("帝", "đấy"), ("社", "xã"), ("支", "chi"), ("𡶀", "núi"), 
    ("𦒹", "sáu"), ("方", "phương"), ("紙", "giấy"), ("𬙞", "bảy"), ("𩵜", "cá"), ("亞", "á"), ("台", "thay"), ("𨢇", "rượu"), 
    ("息", "tức"), ("𡚢", "to"), ("𠅳", "quên"), ("引", "dẫn"), ("律", "luật"), ("上", "thượng"), ("䬔", "gió"), ("徐", "chờ"), 
    ("見", "kiến"), ("動", "động"), ("𠋥", "mày"), ("盤", "bàn"), ("搬", "bàn"), ("島", "đảo"), ("𩅹", "mưa"), ("業", "nghiệp"), 
    ("𠋺", "tao"), ("姅", "nửa"), ("𨑮", "mười"), ("𥩯", "dựng"), ("𠰺", "dạy"), ("經", "kinh"), ("將", "tướng"), ("綠", "lục"), 
    ("𥄬", "ngủ"), ("濟", "tế"), ("際", "tế"), ("戰", "chiến"), ("焒", "lửa"), ("𤳇", "trai"), ("感", "cảm"), ("佛", "phật"), 
    ("哭", "khóc"), ("府", "phủ"), ("不", "bất"), ("品", "phẩm"), ("究", "cứu"), ("林", "lâm"), ("功", "công"), ("重", "trọng"), 
    ("𡏦", "xây"), ("拖", "đỡ"), ("包", "bao"), ("體", "thể"), ("値", "trị"), ("治", "trị"), ("結", "kết"), ("𧖱", "máu"), 
    ("十", "thập"), ("歐", "âu"), ("先", "tiên"), ("仙", "tiên"), ("下", "hạ"), ("㹥", "chó"), ("油", "dầu"), ("沙", "sa"), 
    ("店", "tiệm"), ("𢜠", "mừng"), ("發", "phát"), ("萻", "ấm"), ("試", "thử"), ("此", "thử"), ("𪀄", "chim"), ("彈", "đàn"), 
    ("老", "lão"), ("割", "cắt"), ("船", "thuyền"), ("味", "mùi"), ("𢺺", "chia"), ("祖", "tổ"), ("組", "tổ"), ("粓", "cơm"), 
    ("域", "vực"), ("料", "liệu")
]

grade4 = [
    ("枝", "chi"), ("産", "sản"), ("咖", "cà"), ("啡", "phê"), ("查", "tra"), ("看", "khán"), ("決", "quyết"), ("攎", "lựa"), 
    ("壓", "áp"), ("進", "tiến"), ("互", "hỗ"), ("銀", "ngân"), ("祠", "thờ"), ("險", "hiểm"), ("思", "tư"), ("皇", "hoàng"), 
    ("險", "hiểm"), ("習", "tập"), ("改", "cải"), ("良", "lương"), ("面", "diện"), ("積", "tích"), ("集", "tập"), ("規", "quy"), 
    ("廷", "đình"), ("合", "hợp"), ("織", "chức"), ("鉑", "bạc"), ("者", "giả"), ("水", "thuỷ"), ("俗", "tục"), ("媽", "má"), 
    ("楛", "gỗ"), ("交", "giao"), ("畑", "đèn"), ("𢷮", "đổi"), ("舉", "cử"), ("筆", "bút"), ("案", "án"), ("領", "lãnh"), 
    ("作", "tác"), ("馬", "mã"), ("色", "sắc"), ("迷", "mê"), ("氣", "khí"), ("師", "sư"), ("𠰘", "miệng"), ("𤙭", "bò"), 
    ("婦", "phụ"), ("輔", "phụ"), ("暫", "tạm"), ("史", "sử"), ("啊", "à"), ("鬥", "đấu"), ("斗", "đấu"), ("苦", "khổ"), 
    ("惜", "tiếc"), ("反", "phản"), ("果", "quả"), ("椒", "tiêu"), ("教", "giáo"), ("精", "tinh"), ("星", "tinh"), ("科", "khoa"), 
    ("量", "lượng"), ("茶", "trà"), ("縁", "duyên"), ("置", "trí"), ("纇", "lỗi"), ("助", "trợ"), ("𠔭", "tám"), ("小", "tiểu"), 
    ("後", "hậu"), ("𠊚", "ngài"), ("入", "nhập"), ("能", "năng"), ("𠦳", "nghìn"), ("葻", "bông"), ("目", "mục"), ("𠃩", "chín"), 
    ("𤯆", "ngon"), ("𩄲", "mây"), ("呌", "kêu"), ("𦝄", "trăng"), ("嘲", "chào"), ("獨", "độc"), ("危", "nguy"), ("章", "chương"), 
    ("妸", "gã"), ("音", "âm"), ("陰", "âm"), ("提", "đề"), ("題", "đề"), ("籺", "hạt"), ("萬", "vạn"), ("制", "chế"), 
    ("製", "chế"), ("典", "điển"), ("絏", "dây"), ("瓊", "quỳnh"), ("力", "lực"), ("内", "nội"), ("待", "đợi"), ("多", "đa"), 
    ("猫", "mèo"), ("唯", "dạ"), ("碁", "cờ"), ("旗", "cờ"), ("要", "yếu"), ("口", "khẩu"), ("恩", "ơn"), ("限", "hạn"), 
    ("媒", "môi"), ("證", "chứng"), ("䏾", "bụng"), ("響", "hưởng"), ("節", "tiết"), ("𣟮", "mềm"), ("福", "phước"), ("地", "địa"), 
    ("間", "gian"), ("土", "thổ"), ("寔", "thiệt"), ("競", "cạnh"), ("址", "chỉ"), ("失", "thất"), ("曆", "lịch"), ("歷", "lịch"), 
    ("杏", "hạnh"), ("幸", "hạnh"), ("出", "xuất"), ("及", "cập"), ("𥾘", "sợi"), ("急", "gấp"), ("算", "toán"), ("夾", "giáp"), 
    ("𠁦", "trúng"), ("漢", "hán"), ("坊", "phường"), ("英", "anh"), ("語", "ngữ"), ("二", "nhì"), ("豫", "dựa"), ("盒", "hộp"), 
    ("嫩", "non"), ("𡽫", "non"), ("論", "luận"), ("蓮", "sen"), ("祝", "chúc"), ("展", "triển"), ("𡉕", "hòn"), ("件", "kiện"), 
    ("近", "cận"), ("巾", "khăn"), ("舍", "xá"), ("詞", "từ"), ("𢩮", "dắt"), ("𡎝", "cõi"), ("畢", "tất"), ("必", "tất"), 
    ("第", "đệ"), ("營", "doanh"), ("火", "hoả"), ("喂", "ôi"), ("得", "đắc"), ("使", "sứ"), ("𤄯", "trong"), ("𧿆", "dãy"), 
    ("𠳐", "vâng"), ("然", "nhiên"), ("言", "ngôn"), ("係", "hệ"), ("系", "hệ"), ("衛", "vệ"), ("伵", "tớ"), ("魚", "ngư"), 
    ("執", "chấp"), ("斤", "cân"), ("劸", "khoẻ")
]

animal_list = [
    ("𤙭", "bò"), ("𤞨", "bò"), ("𩵜", "cá"), ("𢇟", "gà"), ("㹥", "chó"), ("猫", "mèo"), ("𤡒", "chuột"), ("𦦳", "hổ"), 
    ("兔", "thỏ"), ("龍", "long"), ("蛇", "xà"), ("馬", "ngựa"), ("󰍐", "dê"), ("𫅕", "dê"), ("𤠅", "voi"), ("𤢇", "voi"), 
    ("𪀄", "chim"), ("𪀄", "chim"), ("𪀄", "chim"), ("𬸯", "vịt"), ("𬷹", "gà"), ("𪅥", "vạc"), ("鸜", "cò"), ("𪅫", "vạc"), 
    ("𪅑", "quạ"), ("𪅘", "cú"), ("𪀆", "sẻ"), ("燕", "yến"), ("雁", "nhạn"), ("孔雀", "khổng tước"), ("鶴", "hạc"), ("𬸼", "nai"), 
    ("鹿", "lộc"), ("𤞼", "lợn"), ("豕", "thỉ"), ("牛", "ngưu"), ("𬍆", "lợn"), ("𬍑", "dê"), ("𤞨", "bò"), ("𤙭", "bò"), 
    ("𤠅", "voi"), ("𤢇", "voi"), ("𬸼", "nai"), ("𪅥", "vạc"), ("𪅫", "vạc"), ("𪀄", "chim"), ("𩵜", "cá"), ("𩵜", "cá"), 
    ("𦦳", "hổ"), ("𪅑", "quạ")
]

# Kinh Tin Kính (Apostles' Creed) from Borg.tonch.18, an 18th-century
# Vietnamese Catholic catechism. Each tuple is (Nôm, Quốc ngữ, English) for one
# sentence-level segment. Source files:
#   borg-tonch-18-nom.txt:256, split on 。
#   borg-tonch-18-qn.txt:291, split on ". " (footnote markers stripped)
# English follows the segmentation of the Vietnamese text (which splits the
# standard creed phrase "the holy Catholic Church" across three lines because
# the transliteration "San-ta / Y-ghê-rê-gia / Ca-tô-li-ca" sits on three lines).
borg_tonch_18_kinh_tin_kinh = [
    ("碎信敬姚吒咍論丕", "Tôi tin kính Deu Cha hay trọn vậy", "I believe in God the Father almighty"),
    ("孕𢧚𡗶坦", "dựng nên Trời Đất", "creator of Heaven and Earth"),
    ("碎信敬沒昆姚吒", "Tôi tin kính một Con Deu Cha", "I believe in the one Son of God the Father"),
    ("支秋基移吹蘇", "Giê-su Khi-rê-xi-tô", "Jesus Christ"),
    ("主眾碎", "Chúa chúng tôi", "our Lord"),
    ("碎信固法丕𠫾蘇山蘇", "Tôi tin có phép Phi-ri-tô San-tô", "I believe by the power of the Holy Spirit"),
    ("聖瑪𠫾亞召胎", "thánh Ma-ri-a chịu thai", "the holy Mary conceived"),
    ("麻生𦝉童貞", "mà sinh đẻ đồng trinh", "and gave birth as a virgin"),
    ("碎信所召難", "Tôi tin thửa chịu nạn", "I believe that he suffered"),
    ("蒸時官", "chưng thì quan", "in the time of the official"),
    ("封尸烏丕羅蘇", "Phong-thi-ô Phi-la-tô", "Pontius Pilate"),
    ("棟釘閣抅椊", "đóng đinh gác Câu-rút", "was nailed to the Cross"),
    ("折麻卞垃", "chết mà bèn lấp", "died and was buried"),
    ("碎信所𠖈地獄", "Tôi tin thửa xuống Địa ngục", "I believe that he descended into Hell"),
    ("㝵次𠀧", "Ngày thứ ba", "on the third day"),
    ("𪽝中几折吏𤯩", "Bởi trong kẻ chết lại sống", "he rose again from among the dead"),
    ("碎信所蓮𡗶", "Tôi tin thửa lên Trời", "I believe that he ascended into Heaven"),
    ("御边右姚吒咍論丕", "ngự bên hữu Deu Cha hay trọn vậy", "and is seated at the right hand of God the Father almighty"),
    ("碎信所㝵婁", "Tôi tin thửa ngày sau", "I believe that on the last day"),
    ("𪽝𡗶吏𠖈", "bởi Trời lại xuống", "he will come down again from Heaven"),
    ("判察几𤯩喡几折", "phán xét kẻ sống và kẻ chết", "to judge the living and the dead"),
    ("碎信丕𠫾蘇山蘇", "Tôi tin Phi-ri-tô San-tô", "I believe in the Holy Spirit"),
    ("碎信固山些", "Tôi tin có San-ta", "I believe in the holy"),
    ("依計移加", "Y-ghê-rê-gia", "Church"),
    ("𬞢蘇離𬞢", "Ca-tô-li-ca", "Catholic"),
    ("各聖共通功", "các thánh cùng thông công", "the communion of saints"),
    ("碎信蒸赦罪", "Tôi tin chưng tha tội", "I believe in the forgiveness of sins"),
    ("碎信蒸類𠊚吏𤯩", "Tôi tin chưng loài người lại sống", "I believe in the resurrection of mankind"),
    ("碎信恒𤯩丕", "Tôi tin hằng sống vậy", "I believe in life everlasting"),
    ("亞綿", "A-men", "Amen"),
]

# Kinh Thiên Chúa (Lord's Prayer / Pater Noster) from Borg.tonch.18.
# Source: borg-tonch-18-nom.txt:248 / borg-tonch-18-qn.txt:283 (single line each).
borg_tonch_18_kinh_thien_chua = [
    ("眾碎𥛉恩天地真主", "Chúng tôi lạy ơn Thiên Địa Chân Chúa", "We worship the True Lord of Heaven and Earth"),
    ("於𨕭𡗶羅吒眾碎", "ở trên Trời là Cha chúng tôi", "who is in Heaven, our Father"),
    ("眾碎願", "Chúng tôi nguyện", "We pray"),
    ("名吒奇創", "danh Cha cả sáng", "hallowed be your name"),
    ("國吒治旦", "quốc Cha trị đến", "your kingdom come"),
    ("𠳐𧘇吒𠁑坦", "vâng ý Cha dưới đất", "your will be done on earth"),
    ("平𨕭𡗶丕", "bằng trên Trời vậy", "as it is in Heaven"),
    ("眾碎吀吒", "Chúng tôi xin Cha", "We ask of you, Father"),
    ("𣈙朱眾碎", "rầy cho chúng tôi", "give us"),
    ("恒㝵用堵", "hằng ngày dùng đủ", "our daily bread"),
    ("麻赦女眾碎", "mà tha nợ chúng tôi", "and forgive us our debts"),
    ("平眾碎拱赦", "bằng chúng tôi cũng tha", "as we also forgive"),
    ("几固女眾碎丕", "kẻ có nợ chúng tôi vậy", "those who are indebted to us"),
    ("吀渚底眾碎", "xin chớ để chúng tôi", "and let us not"),
    ("沙蒸感𠴗", "sa chưng cám dỗ", "fall into temptation"),
    ("卞助眾碎", "bèn chữa chúng tôi", "but deliver us"),
    ("蒸事与", "chưng sự dữ", "from evil"),
    ("亞綿", "A-men", "Amen"),
]

# Kinh A-ve (Hail Mary / Ave Maria) from Borg.tonch.18.
# Source: borg-tonch-18-nom.txt:252 / borg-tonch-18-qn.txt:287 (single line each
# after the [18r] page break; the prayer body itself is contiguous).
borg_tonch_18_kinh_ave = [
    ("亞蟡瑪𠫾亞", "A-ve Ma-ri-a", "Hail Mary"),
    ("苔𬞢囉沙", "đầy Ga-ra-sa", "full of grace"),
    ("主姚 於共妑", "Chúa Deu ở cùng bà", "the Lord is with thee"),
    ("女中妑固福邏", "nữ trung bà có phúc lạ", "blessed art thou among women"),
    ("妑胎子支秋", "bà thai tử Giê-su", "the fruit of thy womb, Jesus"),
    ("歉福邏", "gồm phúc lạ", "is also blessed"),
    ("山些瑪𠫾亞", "San-ta Ma-ri-a", "Holy Mary"),
    ("德媄主姚", "Đức Mẹ Chúa Deu", "Mother of God"),
    ("求朱眾碎", "cầu cho chúng tôi", "pray for us"),
    ("几固罪欺𠉞", "kẻ có tội khi nay", "sinners, now"),
    ("及臣等死候", "cập thần đẳng tử hầu", "and at the hour of our death"),
    ("亞綿", "A-men", "Amen"),
]
